# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedFace',
            fields=[
                ('face_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('age', models.FloatField()),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('rect_top', models.IntegerField()),
                ('rect_left', models.IntegerField()),
                ('rect_width', models.IntegerField()),
                ('rect_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('file_path', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='detectedface',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AddField(
            model_name='detectedface',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Picture'),
        ),
    ]
